version: '3.8'
services:
  database:
    image:  postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
    ports:
      - "5432:5432"
    stop_signal: SIGTERM
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    command: "entrypoint.sh" 
    depends_on:
      - database
    environment:
      #RAILS_ENV: production
      #RAILS_SERVE_STATIC_FILES: true
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_HOST: database 
      DATABASE_NAME: basic_application_db
      #SETUP_DB: true
      # HOST_URL: http:/host.com
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

volumes:
  postgres-data: