
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: database
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: basic_application_db
